"用户名不能为空，请重新输入" - "Username cannot be empty, please re-enter"
"密码不能为空，请重新输入" - "Password cannot be empty, please re-enter"
"正在登录，请稍等.." - "Logging in, please wait.."
"登录成功，正在进入系统.." - "Login successful, entering the system.."
"可分解哈希币" - "Can be decomposed into Hash coins"
"购买时间" - "Purchase time"
"分解时间" - "Decomposition time"
"完成" - "Completed"
"查看物流" - "View logistics"
"确认收货" - "Confirm receipt"
"没有更多了" - "No more items"
"单号" - "Order number"
"分解时间" - "Decomposition time"
"完成" - "Completed"
"分解" - "Decompose"
"提货" - "Pick up"
"确定" - "Confirm"
"兑换成功" - "Exchange Successful"
"提货成功,发货中" - "Pick-up Successful, Shipping in Progress"
"停止滚动" - "Stop Scrolling"
"请填写收货人姓名" - "Please enter the recipient's name"
"请填写手机号码" - "Please enter the phone number"
"选择地区" - "Select Region"
"请填写详细地址" - "Please enter the detailed address"
"修改成功" - "Modification Successful"
"省份" - "Province"
"城市" - "City"
"县区" - "District"
"请查看用户协议" - "Please read the user agreement"
"商品错误" - "Product error"