"确认订单" - "Confirm Order"
"请先添加地址" - "Please Add Address First"
"可分解哈希币" - "Can be decomposed into Hash Coins"
"运费" - "Shipping Fee"
"共1件 | 合计" - "Total 1 Item | Total"
"若完成交易代表您已同意以下约定" - "Completing the transaction means you agree to the following terms"
"港澳台地区及部分偏远地区会无法配送" - "Delivery is not available to Hong Kong, Macau, Taiwan, and some remote areas"
"受疫情等因素影响，多地物流公司接单和派送受影响，物流时效性有所延长，还请谅解，如有疑问请随时联系在线客服咨询" - "Due to the pandemic and other factors, the order acceptance and delivery by logistics companies in many places are affected, leading to extended delivery times. Please understand and feel free to contact online customer service for inquiries"
"由于显示器，拍照和做图的过程中，产品可能发生颜色偏差，具体请以实物为准" - "Color deviation may occur during the display, photographing, and image processing stages. Please refer to the actual product"
"确认提货" - "Confirm Pickup"
"余额不足" - "Insufficient Balance"