<html lang="zh-CN" style="--status-bar-height:0px; --top-window-height:0px; --window-left:0px; --window-right:0px; --window-margin:0px; --window-top:calc(var(--top-window-height) + calc(44px + env(safe-area-inset-top))); --window-bottom:0px;"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>优惠券</title><meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=cover"><link rel="stylesheet" href="./static/index.css"><style type="text/css">@charset "UTF-8";
.main-center-flex[data-v-7a78d4df]{display:flex;align-items:center;justify-content:center}
.main-start-flex[data-v-7a78d4df]{display:flex;align-items:center;justify-content:flex-start}.main-align-start-flex[data-v-7a78d4df]{display:flex;align-items:flex-start;justify-content:center}.main-start-align-start-flex[data-v-7a78d4df]{display:flex;align-items:flex-start;justify-content:flex-start}.main-start-align-end-flex[data-v-7a78d4df]{display:flex;align-items:flex-end;justify-content:flex-start}.main-end-flex[data-v-7a78d4df]{display:flex;align-items:center;justify-content:flex-end}.main-space-between[data-v-7a78d4df]{display:flex;align-items:center;justify-content:space-between}.main-space-around[data-v-7a78d4df]{display:flex;align-items:center;justify-content:space-around}.main-center-align-end[data-v-7a78d4df]{display:flex;align-items:flex-end;justify-content:center}.column-start-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:center;justify-content:flex-start}.column-end-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:center;justify-content:flex-end}.column-align-start-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:flex-start;justify-content:center}.column-align-end-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:flex-end;justify-content:center}.column-align-start-space-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:flex-start;justify-content:space-between}.column-center-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:center;justify-content:center}.column-space-between[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:center;justify-content:space-between}.text-ellipsis[data-v-7a78d4df]{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.text-ellipsis_2[data-v-7a78d4df]{display:-webkit-box;overflow:hidden;
  /*! autoprefixer: off; */-webkit-box-orient:vertical;-webkit-line-clamp:2}.box-grow-0[data-v-7a78d4df]{
min-width:0;flex-grow:0;flex-shrink:0}.box-grow-1[data-v-7a78d4df]{
min-width:0;flex-grow:1;flex-shrink:1}.dir-left-nowrap[data-v-7a78d4df]{
display:flex;flex-direction:row;flex-wrap:nowrap}.clear-button[data-v-7a78d4df]::after{border:none}.clear-button[data-v-7a78d4df]{position:relative;display:block;margin-left:auto;margin-right:auto;padding-left:0;padding-right:0;box-sizing:border-box;text-align:center;text-decoration:none;line-height:1.35;-webkit-tap-highlight-color:transparent;overflow:hidden;color:#000;background-color:#fff;width:100%;height:100%;border-radius:0}div[data-v-7a78d4df], uni-scroll-view[data-v-7a78d4df], uni-swiper-item[data-v-7a78d4df]{display:flex;flex-direction:column;flex-shrink:0;flex-grow:0;flex-basis:auto;align-items:stretch;align-content:flex-start}.u-tabs__wrapper[data-v-7a78d4df]{display:flex;flex-direction:row;align-items:center}.u-tabs__wrapper__scroll-view-wrapper[data-v-7a78d4df]{flex:1;overflow:auto hidden}.u-tabs__wrapper__scroll-view[data-v-7a78d4df]{display:flex;flex-direction:row;flex:1}.u-tabs__wrapper__nav[data-v-7a78d4df]{display:flex;flex-direction:row;position:relative}.u-tabs__wrapper__nav__item[data-v-7a78d4df]{padding:0 11px;display:flex;flex-direction:row;align-items:center;justify-content:center}.u-tabs__wrapper__nav__item--disabled[data-v-7a78d4df]{cursor:not-allowed}.u-tabs__wrapper__nav__item__text[data-v-7a78d4df]{font-size:15px;color:#606266}.u-tabs__wrapper__nav__item__text--disabled[data-v-7a78d4df]{color:#c8c9cc!important}.u-tabs__wrapper__nav__line[data-v-7a78d4df]{height:3px;background:#3c9cff;width:30px;position:absolute;bottom:2px;border-radius:100px;transition-property:-webkit-transform;transition-property:transform;transition-property:transform,-webkit-transform;transition-duration:.3s}</style><style type="text/css">@charset "UTF-8";
.main-center-flex{display:flex;align-items:center;justify-content:center}
.main-start-flex{display:flex;align-items:center;justify-content:flex-start}.main-align-start-flex{display:flex;align-items:flex-start;justify-content:center}.main-start-align-start-flex{display:flex;align-items:flex-start;justify-content:flex-start}.main-start-align-end-flex{display:flex;align-items:flex-end;justify-content:flex-start}.main-end-flex{display:flex;align-items:center;justify-content:flex-end}.main-space-between{display:flex;align-items:center;justify-content:space-between}.main-space-around{display:flex;align-items:center;justify-content:space-around}.main-center-align-end{display:flex;align-items:flex-end;justify-content:center}.column-start-flex{display:flex;flex-direction:column;align-items:center;justify-content:flex-start}.column-end-flex{display:flex;flex-direction:column;align-items:center;justify-content:flex-end}.column-align-start-flex{display:flex;flex-direction:column;align-items:flex-start;justify-content:center}.column-align-end-flex{display:flex;flex-direction:column;align-items:flex-end;justify-content:center}.column-align-start-space-flex{display:flex;flex-direction:column;align-items:flex-start;justify-content:space-between}.column-center-flex{display:flex;flex-direction:column;align-items:center;justify-content:center}.column-space-between{display:flex;flex-direction:column;align-items:center;justify-content:space-between}.text-ellipsis{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.text-ellipsis_2{display:-webkit-box;overflow:hidden;
  /*! autoprefixer: off; */-webkit-box-orient:vertical;-webkit-line-clamp:2}.box-grow-0{
min-width:0;flex-grow:0;flex-shrink:0}.box-grow-1{
min-width:0;flex-grow:1;flex-shrink:1}.dir-left-nowrap{
display:flex;flex-direction:row;flex-wrap:nowrap}.clear-button::after{border:none}.clear-button{position:relative;display:block;margin-left:auto;margin-right:auto;padding-left:0;padding-right:0;box-sizing:border-box;text-align:center;text-decoration:none;line-height:1.35;-webkit-tap-highlight-color:transparent;overflow:hidden;color:#000;background-color:#fff;width:100%;height:100%;border-radius:0}.container{width:100%;background:linear-gradient(90deg,#f2f0ff,#edebff,#f3f8ff);z-index:1}.container .head{width:100%;height:40px;background:#fff}.container .scroll-view{height:calc(100vh - 45px);padding-bottom:env(safe-area-inset-bottom);background:linear-gradient(180deg,#f0efff,#f2f6ff)}.container .list-container{width:100%;height:100%;padding:15px;background:linear-gradient(180deg,#f0efff,#f2f6ff)}.container .list-item{width:100%;height:100px;background-size:100% 100%;margin-bottom:15px;display:flex}.container .cannot-use{-webkit-filter:grayscale(1);filter:grayscale(1);opacity:.7;pointer-events:none}.container .list-item-left{width:94px;height:100%}.container .coupon-price{font-size:32px;font-family:PingFang SC-Semibold;font-weight:Semibold;color:#fff}.container .coupon-price > uni-text{font-size:16px}.container .coupon-condition{font-size:12px;font-family:PingFang SC-Regular;font-weight:Regular;color:#fff}.container .list-item-center{width:calc(100% - 94px - 80px);height:100%;padding:0 2px 0 12px}.container .list-item-center > div{width:100%}.container .coupon-name{font-size:14px;font-family:PingFang SC-Medium;font-weight:600;color:#54575f}.container .has-coupon-name{opacity:1%}.container .coupon-range{padding-top:5px;font-size:12px;font-family:PingFang SC-Regular;font-weight:Regular;color:#999}.container .coupon-time{font-size:10px;font-family:Source Han Sans CN;font-weight:400;color:#999;margin-top:10px}.container .list-item-right{width:80px;height:100%}.container .list-item-right .btn-class{width:60px;height:22px;border-radius:11px;text-align:center;font-size:12px;font-family:PingFangHK-Regular;white-space:nowrap;font-weight:500;line-height:21px}.container .list-item-right .coupon-btn{border:1px solid #8f09ee;overflow-wrap:break-word;color:#8f09ec}.container .list-item-right .discount-btn{border:1px solid #ee8b34;overflow-wrap:break-word;color:#ee8c34}.container .list-item-right .has-use-img{width:68px;height:56px}.container .buy-button{position:fixed;bottom:0;left:0;padding-bottom:env(safe-area-inset-bottom);width:375px;height:calc(65px + env(safe-area-inset-bottom));background-color:#fff}.container .buy-button .buy-button-detail{width:345px;height:49px;font-size:19px;font-family:BTH;font-weight:400;color:#fbf8ff;text-shadow:0 1px 0 rgba(28,28,27,.33);background:linear-gradient(99deg,#8f0cf2,#b444fe)}
</style>
</head>
<body>
<uni-app><uni-page>
<uni-page-head>
<div class="uni-page-head" style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);">
<div class="uni-page-head-hd" onclick="history.go(-1);"><div class="uni-page-head-btn"><i class="uni-btn-icon" style="color: rgb(0, 0, 0); font-size: 27px;"></i></div>
<div class="uni-page-head-ft"></div>
</div>
<div class="uni-page-head-bd"><div class="uni-page-head__title" style="font-size: 16px; opacity: 1;"> 优惠券 </div>
</div>
<div class="uni-page-head-ft"></div>
</div>
<div class="uni-placeholder"></div>
</uni-page-head><uni-page-wrapper><uni-page-body><div class="container"><div class="head"><div data-v-7a78d4df="" class="u-tabs"><div data-v-7a78d4df="" class="u-tabs__wrapper"><div data-v-7a78d4df="" class="u-tabs__wrapper__scroll-view-wrapper"><uni-scroll-view data-v-7a78d4df="" class="u-tabs__wrapper__scroll-view"><div class="uni-scroll-view"><div class="uni-scroll-view" style="overflow: hidden;"><div class="uni-scroll-view-content"><div data-v-7a78d4df="" class="u-tabs__wrapper__nav"><div data-v-7a78d4df="" class="u-tabs__wrapper__nav__item u-tabs__wrapper__nav__item-0" style="width: 50%; height: 40px; font-size: 14px; font-family: &quot;Source Han Sans CN&quot;; font-weight: 400; color: rgb(153, 153, 153); flex: 1 1 0%;"><uni-text data-v-7a78d4df="" class="u-tabs__wrapper__nav__item__text" style="color: rgb(0, 0, 0); font-family: &quot;Source Han Sans CN&quot;; font-weight: 500;"><span>可用</span></uni-text></div>
<div data-v-7a78d4df="" class="u-tabs__wrapper__nav__item u-tabs__wrapper__nav__item-1" style="width: 50%; height: 40px; font-size: 14px; font-family: &quot;Source Han Sans CN&quot;; font-weight: 400; color: rgb(153, 153, 153); flex: 1 1 0%;"><uni-text data-v-7a78d4df="" class="u-tabs__wrapper__nav__item__text" style="color: rgb(96, 98, 102);"><span>不可用</span></uni-text></div>
<div data-v-7a78d4df="" class="u-tabs__wrapper__nav__line" style="width: 56px; transform: translate(65.75px); transition-duration: 300ms; height: 2px; background:  0% 0% / cover rgb(141, 0, 230);"></div>
</div>
</div>
</div>
</div>
</uni-scroll-view></div>
</div>
</div>
</div>
<uni-scroll-view class="scroll-view"><div class="uni-scroll-view"><div class="uni-scroll-view" style="overflow: hidden auto;"><div class="uni-scroll-view-content"><div class="list-container"></div>
</div>
</div>
</div>
</uni-scroll-view></div>
</uni-page-body></uni-page-wrapper></uni-page></uni-app></body></html>