<html lang="zh-CN" style="--status-bar-height:0px; --top-window-height:0px; --window-left:0px; --window-right:0px; --window-margin:0px; --window-top:calc(var(--top-window-height) + calc(44px + env(safe-area-inset-top))); --window-bottom:0px;">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>我的订单</title>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=cover">
<link rel="stylesheet" href="./static/index.css">
<style type="text/css">@charset "UTF-8";
.main-center-flex[data-v-7a78d4df]{display:flex;align-items:center;justify-content:center}
.main-start-flex[data-v-7a78d4df]{display:flex;align-items:center;justify-content:flex-start}.main-align-start-flex[data-v-7a78d4df]{display:flex;align-items:flex-start;justify-content:center}.main-start-align-start-flex[data-v-7a78d4df]{display:flex;align-items:flex-start;justify-content:flex-start}.main-start-align-end-flex[data-v-7a78d4df]{display:flex;align-items:flex-end;justify-content:flex-start}.main-end-flex[data-v-7a78d4df]{display:flex;align-items:center;justify-content:flex-end}.main-space-between[data-v-7a78d4df]{display:flex;align-items:center;justify-content:space-between}.main-space-around[data-v-7a78d4df]{display:flex;align-items:center;justify-content:space-around}.main-center-align-end[data-v-7a78d4df]{display:flex;align-items:flex-end;justify-content:center}.column-start-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:center;justify-content:flex-start}.column-end-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:center;justify-content:flex-end}.column-align-start-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:flex-start;justify-content:center}.column-align-end-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:flex-end;justify-content:center}.column-align-start-space-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:flex-start;justify-content:space-between}.column-center-flex[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:center;justify-content:center}.column-space-between[data-v-7a78d4df]{display:flex;flex-direction:column;align-items:center;justify-content:space-between}.text-ellipsis[data-v-7a78d4df]{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.text-ellipsis_2[data-v-7a78d4df]{display:-webkit-box;overflow:hidden;
  /*! autoprefixer: off; */-webkit-box-orient:vertical;-webkit-line-clamp:2}.box-grow-0[data-v-7a78d4df]{
min-width:0;flex-grow:0;flex-shrink:0}.box-grow-1[data-v-7a78d4df]{min-width:0;flex-grow:1;flex-shrink:1}.dir-left-nowrap[data-v-7a78d4df]{
display:flex;flex-direction:row;flex-wrap:nowrap}.clear-button[data-v-7a78d4df]::after{border:none}.clear-button[data-v-7a78d4df]{position:relative;display:block;margin-left:auto;margin-right:auto;padding-left:0;padding-right:0;box-sizing:border-box;text-align:center;text-decoration:none;line-height:1.35;-webkit-tap-highlight-color:transparent;overflow:hidden;color:#000;background-color:#fff;width:100%;height:100%;border-radius:0}div[data-v-7a78d4df], uni-scroll-view[data-v-7a78d4df], uni-swiper-item[data-v-7a78d4df]{display:flex;flex-direction:column;flex-shrink:0;flex-grow:0;flex-basis:auto;align-items:stretch;align-content:flex-start}.u-tabs__wrapper[data-v-7a78d4df]{display:flex;flex-direction:row;align-items:center}.u-tabs__wrapper__scroll-view-wrapper[data-v-7a78d4df]{flex:1;overflow:auto hidden}.u-tabs__wrapper__scroll-view[data-v-7a78d4df]{display:flex;flex-direction:row;flex:1}.u-tabs__wrapper__nav[data-v-7a78d4df]{display:flex;flex-direction:row;position:relative}.u-tabs__wrapper__nav__item[data-v-7a78d4df]{padding:0 11px;display:flex;flex-direction:row;align-items:center;justify-content:center}.u-tabs__wrapper__nav__item--disabled[data-v-7a78d4df]{cursor:not-allowed}.u-tabs__wrapper__nav__item__text[data-v-7a78d4df]{font-size:15px;color:#606266}.u-tabs__wrapper__nav__item__text--disabled[data-v-7a78d4df]{color:#c8c9cc!important}.u-tabs__wrapper__nav__line[data-v-7a78d4df]{height:3px;background:#3c9cff;width:30px;position:absolute;bottom:2px;border-radius:100px;transition-property:-webkit-transform;transition-property:transform;transition-property:transform,-webkit-transform;transition-duration:.3s}</style><style type="text/css">.uni-app--showtabbar uni-page-wrapper {display: block;height: calc(100% - 60px);height: calc(100% - 60px - constant(safe-area-inset-bottom));height: calc(100% - 60px - env(safe-area-inset-bottom));}
.uni-app--showtabbar uni-page-wrapper::after {content: "";display: block;width: 100%;
height: 60px;height: calc(60px + constant(safe-area-inset-bottom));height: calc(60px + env(safe-area-inset-bottom));}
.uni-app--showtabbar uni-page-head[uni-page-head-type="default"] ~ uni-page-wrapper {height: calc(100% - 44px - 60px);height: calc(100% - 44px - constant(safe-area-inset-top) - 60px - constant(safe-area-inset-bottom));height: calc(100% - 44px - env(safe-area-inset-top) - 60px - env(safe-area-inset-bottom));}</style><style type="text/css">.container[data-v-0d92b71b]{width:375px;	/* height: 100vh; */	/* position: fixed; */	/* 	top: 0;	left: 0; */background:linear-gradient(90deg,#f2f0ff,#edebff,#f3f8ff)}.img[data-v-0d92b71b]{height:100%;width:100%;display:flex;align-items:center;justify-content:center;flex-direction:column;margin-top:50%}.image[data-v-0d92b71b]{width:98px;height:98px}.content[data-v-0d92b71b]{margin-top:15px;color:#afafaf;font-size:16px}</style><style type="text/css">.container{width:100%;min-height:100vh;background:linear-gradient(90deg,#f2f0ff,#edebff,#f3f8ff);position:relative}.head{width:100%;height:40px;background:#fff}.list-container{width:100%;height:calc(100% - 60px);padding:15px;position:relative}.list-item{width:100%;background:#fff;margin-bottom:15px}.list-head{height:37px;width:100%;padding:12px;font-size:12px;font-family:Source Han Sans CN;font-weight:400;color:#999}.list-body{height:117px;width:100%;padding:15px}.list-body-left{height:100%;width:87px}.list-body-right{height:100%;width:calc(100% - 87px);padding:5px}.goods-price{height:34%;width:100%}.goods-name{font-size:14px;font-family:Source Han Sans CN;font-weight:400;color:#333}.goods-price{display:flex;justify-content:space-between;align-items:flex-end}.goods-price>div:first-child{font-size:17px;font-family:Abel;font-weight:400;color:#333}.goods-price>div:first-child uni-text{font-size:10px;font-family:Source Han Sans CN;font-weight:400;color:#333}.goods-price>div:last-child{font-size:10px;font-family:Source Han Sans CN;font-weight:400;color:#999}.list-foot{height:75px;width:100%;padding:15px}.goods-num{font-size:12px;font-family:Source Han Sans CN;font-weight:400;color:#999}.goods-total-price{font-size:12px;font-family:Source Han Sans CN;font-weight:400;color:#333;align-items:baseline}.goods-total-price>uni-text:last-child{font-size:20px;font-family:Abel;font-weight:400;color:#333}.list-opertaion{width:100%;padding-right:10px}.list-button-item{margin:10px 0 10px 15px;width:77px;height:30px;font-size:12px;font-family:Source Han Sans CN;font-weight:500;color:#333}.cancel-order,
.confirm-receive{border:1px solid #f8f8f8}.pay-order{background:#3f3f42;font-size:12px;font-family:Source Han Sans CN;font-weight:500;color:#fff}</style>
</head>
<body>
<uni-app><uni-page>
<uni-page-head><div class="uni-page-head" style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);">
<div class="uni-page-head-hd" onclick="history.go(-1);"><div class="uni-page-head-btn"><i class="uni-btn-icon" style="color: rgb(0, 0, 0); font-size: 27px;"></i></div>
<div class="uni-page-head-ft"></div>
</div>
<div class="uni-page-head-bd"><div class="uni-page-head__title" style="font-size: 16px; opacity: 1;"><!----> 我的订单 </div>
</div>
<!----><div class="uni-page-head-ft"></div>
</div>
<div class="uni-placeholder"></div>
</uni-page-head>
<uni-page-wrapper><uni-page-body><div class="container"><div class="head"><div data-v-7a78d4df="" class="u-tabs"><div data-v-7a78d4df="" class="u-tabs__wrapper"><div data-v-7a78d4df="" class="u-tabs__wrapper__scroll-view-wrapper"><uni-scroll-view data-v-7a78d4df="" class="u-tabs__wrapper__scroll-view"><div class="uni-scroll-view"><div class="uni-scroll-view" style="overflow: hidden;"><div class="uni-scroll-view-content"><!----><div data-v-7a78d4df="" class="u-tabs__wrapper__nav"><div data-v-7a78d4df="" class="u-tabs__wrapper__nav__item u-tabs__wrapper__nav__item-0" style="width: 25%; height: 40px; font-size: 14px; font-family: &quot;Source Han Sans CN&quot;; font-weight: 400; color: rgb(153, 153, 153); flex: 1 1 0%;"><uni-text data-v-7a78d4df="" class="u-tabs__wrapper__nav__item__text" style="font-family: &quot;Source Han Sans CN&quot;; font-weight: 500; color: rgb(0, 0, 0);"><span>待付款</span></uni-text><!----></div>
<div data-v-7a78d4df="" class="u-tabs__wrapper__nav__item u-tabs__wrapper__nav__item-1" style="width: 25%; height: 40px; font-size: 14px; font-family: &quot;Source Han Sans CN&quot;; font-weight: 400; color: rgb(153, 153, 153); flex: 1 1 0%;"><uni-text data-v-7a78d4df="" class="u-tabs__wrapper__nav__item__text" style="color: rgb(96, 98, 102);"><span>待发货</span></uni-text><!----></div>
<div data-v-7a78d4df="" class="u-tabs__wrapper__nav__item u-tabs__wrapper__nav__item-2" style="width: 25%; height: 40px; font-size: 14px; font-family: &quot;Source Han Sans CN&quot;; font-weight: 400; color: rgb(153, 153, 153); flex: 1 1 0%;"><uni-text data-v-7a78d4df="" class="u-tabs__wrapper__nav__item__text" style="color: rgb(96, 98, 102);"><span>待收货</span></uni-text><!----></div>
<div data-v-7a78d4df="" class="u-tabs__wrapper__nav__line" style="width: 20px; transform: translate(52.5px); transition-duration: 300ms; height: 2px; background:  0% 0% / cover rgb(51, 51, 51);"></div>
</div>
</div>
</div>
</div>
</uni-scroll-view></div>
</div>
</div>
</div>
<!----><div data-v-0d92b71b="" class="container default"><logistics data-v-0d92b71b="" wlinfo="[object Object]"></logistics><div data-v-0d92b71b="" class="img"><uni-image data-v-0d92b71b="" class="image"><div style="background-image: url(&quot;./static/img/default.44927131.png&quot;); background-position: 0% 0%; background-size: 100% 100%; background-repeat: no-repeat;"></div>
<!----><img src="./static/img/default.44927131.png" draggable="false"></uni-image><div data-v-0d92b71b="" class="content">暂无信息</div>
</div>
</div>
</div>
</uni-page-body></uni-page-wrapper></uni-page></uni-app></body></html>